@startuml Diagrama de Secuencia
title Diagrama de Secuencia

skinparam monochrome true
hide footbox

participant Actor
participant "cemento:Cemento" as Cemento
participant "pintura:Pintura" as Pintura
participant "canio:Canios" as Canios
participant "nuevaCasa:Casa" as Casa
participant "almacen:Almacen" as Almacen

create Cemento
Actor -> Cemento: Cemento(100)

create Pintura
Actor -> Pintura: Pintura(2500)

create Canios
Actor -> Canios: Canios(500)

create Casa
Actor -> Casa: Casa(5)

create Almacen
Actor -> Almacen

activate Almacen

Actor -> Almacen: agregarMateriales(Cemento)
Almacen -> Almacen: add(Cemento)

Actor -> Almacen: agregarMateriales(Pintura)
Almacen -> Almacen: add(Pintura)

Actor -> Almacen: agregarMateriales(Canios)
Almacen -> Almacen: add(Canios)

Actor -> Casa: construirCasa(almacen)

Casa -> Casa: construirBase(almacen)
Casa -> Almacen: usarMaterial(new Cemento(50))
Almacen -> Cemento: restarMaterial(new Cemento(50))

Casa -> Almacen: usarMaterial(new Cemento(10 * ambientes))
Almacen -> Cemento: restarMaterial(new Cemento(10 * ambientes))

Casa -> Almacen: usarMaterial(new Pintura(100 * ambientes))
Almacen -> Pintura: restarMaterial(new Pintura(100 * ambientes))

Casa -> Almacen: usarMaterial(new Canios(500 * ambientes))
Almacen -> Canios: restarMaterial(new Canios(500 * ambientes))

@enduml